### ISSUE TITLE
Function "circuitevolution()" calculates redundant versions of Equivalent-Circuit-Models

### ISSUE THREAD

**Issue by StefanPofahl** [MaximeVH/EquivalentCircuits.jl#12]
Function `"circuitevolution()"` calculates redundant versions of Equivalent-Circuit-Models.
One example is shown below:
R1-[C2,R3]-[C4,R5]
[C1,R2]-[R3,C4]-R5  

Regards,
Stefan

**Comment by MaximeVH** [comment]
I'll close this issue as it refers to a previous version of the package. The current `circuit_evolution` function only outputs a single fittest equivalent electrical circuit model.

Kind regards,
Maxime

**Comment by StefanPofahl** [comment]
Great! :-)
