### ISSUE TITLE
circuitevolution(..., terminals="RCL") includes P but not L

### ISSUE THREAD

**Issue by StefanPofahl** [MaximeVH/EquivalentCircuits.jl#14]
Function `"circuitevolution()"`: 
Optional parameter `terminals` does not work properly,
if I specify: terminals="RCL"
also solutions with P-elements are found.

**Comment by StefanPofahl** [comment]
Could it be that a comma is missing?
![Missing_comma_julia_packages_EquivalentCircuit](https://user-images.githubusercontent.com/65159315/202577113-64481734-3824-472d-a8a1-5b7cb2ce4351.png)

**Comment by StefanPofahl** [comment]
strange, today I cloned your repository by means of the Pkg-Command `dev`:
pkg> dev EquivalentCircuits
now I have two versions on my hard drive:
old:
`C:\Users\[...]\.julia\packages\EquivalentCircuits\6sREk\src\OptimizeParameters.jl`
```
function get_parameter_upper_bound(tree)
    ranges = Dict('R'=>1.0e9,'C'=>10,'L'=>5,'P'=>[1.0e9,1],'+'=>0,'-'=>0) #Dict('R'=>5000,'C'=>0.001,0.01'L'=>1,'P'=>[100,1],'+'=>0,'-'=>0) , Dict('R'=>1.0e9,'C'=>0.01,'L'=>5,'P'=>[1.0e9,1],'+'=>0,'-'=>0)
    return [ranges[node.Type] for node in tree]
end
```
new:
```
function get_parameter_upper_bound(tree)
    ranges = Dict('R'=>1.0e9,'C'=>10,'L'=>5,'P'=>[1.0e9,1],'W'=>1.0e9,'+'=>0,'-'=>0) 
    return [ranges[node.Type] for node in tree]
end
```

**Comment by StefanPofahl** [comment]
I do not why, but I managed to install an old version of EquivalentCircuit.jl
![EquivalentCircuits_old_version](https://user-images.githubusercontent.com/65159315/203380503-e0069a88-d1ae-48f8-9eb4-f6b477a8ff0d.png)

**Comment by MaximeVH** [comment]
Have you encountered this issue with the newest version of the package too? I've run the function several times on the example measurement data with different values for the `terminals` argument, and it seems to work fine so far.

**Comment by StefanPofahl** [comment]
I was not able to reproduce this strange situation.
