### ISSUE TITLE
More Examples

### ISSUE THREAD

**Issue by StefanPofahl** [MaximeVH/EquivalentCircuits.jl#15]
Hi Maxime,

I have made an example [example_investigate_equivalent_circuit_modules.jl](https://github.com/StefanPofahl/EquivalentCircuits.jl/blob/87499b45100019ed31c14e784af16b9cb08f9fb4/examples/example_investigate_equivalent_circuit_modules.jl#L1)  to investigate the characteristics of equivalent circuit elements / terminals.
It would be nice, if you could add something similar to your repository.

Regards,

Stefan

**Comment by MaximeVH** [comment]
I have included your informative examples. In the next release, the `circuitfunction `and `simulateimpedance_noiseless` functions will be exported in the module.
