### ISSUE TITLE
CPE / 'P' is different from definition inside "impedance.py"

### ISSUE THREAD

**Issue by StefanPofahl** [MaximeVH/EquivalentCircuits.jl#16]
Could it be, that the definitions for CPE/'P' are not correct?
see here:
[CPE](https://impedancepy.readthedocs.io/en/latest/circuit-elements.html#impedance.models.circuits.elements.CPE)

**Comment by MaximeVH** [comment]
Unfortunately, there is a lack of standard definitions of Warburg and CPE elements in the literature. There are two different definitions for CPEs in common use, the one derived by Boukamp and the one in Barsoukov and Mcdonald's popular textbook.

For previous work reviewing and comparing equivalent circuits, I have implemented all definitions. They have the same modeling capacity, but if you want to conveniently compare specific parameters to those using a particular definition, I can provide an option for that. I appreciate all your feedback and will be looking into all your suggestions and questions in December.

**Comment by StefanPofahl** [comment]
Here is my proposal for the part in:
`function circuitfunction(Circuit)`
original:
replace(Circuit,match=>"T*(2*π*f)^(-N)"*"*(cos((π*N)*0.5)-sin((π*T)*0.5)im)")
new:
replace(Circuit,match=>"(1/(T*(2im*π*f)^(N)))")

**Comment by StefanPofahl** [comment]
unfortunately, there is a deviation between impedance.py and EquivalentSircuits.jl for more complicated EC.
For a simple one like  "[C1,P2]" there is a perfect match, but for more complicated one like: "[C1-P2,[R3,C4-L5-P6]]", 
there is a difference in the simulation.
Please have a look on my script to compare both packages:
[debug_EquivalentCircuit_Impedance_Simulation.jl](https://github.com/StefanPofahl/EquivalentCircuits.jl/blob/2cea788ecae62cc5670c8b0b228b03d67c1627ac/examples/debug_EquivalentCircuit_Impedance_Simulation.jl)

**Comment by StefanPofahl** [comment]
I have set up a simple script for the simulation of the equivalent circuit: "[C1-P2,R3]"
The results of three different ways are compared:
[example_simple_EquivCirc_including_constant_phase.jl](https://github.com/StefanPofahl/EquivalentCircuits.jl/blob/master/examples/example_simple_EquivCirc_including_constant_phase.jl)

**Comment by StefanPofahl** [comment]
Here is a link regarding the two different approaches:
http://www.consultrsr.net/resources/eis/zarc.htm
