### ISSUE TITLE
Algorithm fails to find optimal parameters for a given equivalent circuit model

### ISSUE THREAD

**Issue by StefanPofahl** [MaximeVH/EquivalentCircuits.jl#18]
Hi Maxime,

today I discussed with a colleague data he has measured and fitted with Gamry-Fit-Software.
He proposed a suitable equivalent circuit model and told me that the Gamry software finds a 
parameter set that is very well suited to fit the data.
I have put the data and a sample code in the sub-folder examples of my fork of your repository, see
[example_iterative_optimization_with_static_equivalent_circuit_model](https://github.com/StefanPofahl/EquivalentCircuits.jl/blob/master/examples/example_iterative_optimization_with_static_equivalent_circuit_model.jl)
I hope you like it and it is useful for your work :-)

**Comment by MaximeVH** [comment]
Hi Stephan,

Thank you very much for all your great contributions; I'll spend some time
incorporating them properly and adding clearer explanations and
documentation to the package, as
well as adding some of the requested functionality and addressing raised
issues.

Best wishes,

Maxime

Op wo 7 dec. 2022 om 11:33 schreef Stefan Pofahl ***@***.***>:

**Comment by StefanPofahl** [comment]
Looking forward to your next version :-)

**Comment by StefanPofahl** [comment]
My code has a bag, I will fix the bug and let you know.

**Comment by StefanPofahl** [comment]
Now the script should do its job properly ...
