### ISSUE TITLE
Compiled App including EquivalentCircuits craches on other computers

### ISSUE THREAD

**Issue by StefanPofahl** [MaximeVH/EquivalentCircuits.jl#20]
Please have a look:
https://github.com/JuliaLang/PackageCompiler.jl/issues/789

Regards,
Stefan

**Comment by StefanPofahl** [comment]
I have opened an issue on the `Tulip` GitHub-Repository.

**Comment by StefanPofahl** [comment]
The `Tulip`-Issue is resolved. :-), see:
https://discourse.julialang.org/t/missing-relocatability-of-tulip/94886/16
But I have still issues with my project that contains your package.
I was able to replace your package and this project can now be compiled into a portable App, please see:
[InteractiveNyquist.jl](https://github.com/StefanPofahl/Stefans_Julia_RePo/blob/main/AppDir/InteractiveNyquist/src/InteractiveNyquist.jl)

**Comment by MaximeVH** [comment]
Hi Stefan,

I'm glad to hear you resolved the issue with your standalone executable. I suppose the difficulty for using EquivalentCircuits here lies in its GeneralizedGenerated.jl dependency?

Regards,
Maxime

**Comment by StefanPofahl** [comment]
Hi Maxime!
I really admire people who write code like: `GeneralizedGenerated.jl`
And at the same time, I observed the the code is not well structured.
I can imagine, that this package is a troublemaker somehow ...
Regards,
Stefan
