### ISSUE TITLE
Use logging instead of `println`

### ISSUE THREAD

**Issue by ma-sadeghi** [MaximeVH/EquivalentCircuits.jl#28]
It'd be great if all the `println`s were replaced with proper logging. This is particularly useful when calling `EquivalentCircuits.jl` from other libraries, to avoid unwanted printing.

**Comment by MaximeVH** [comment]
Good point, I'll look into this

**Comment by MaximeVH** [comment]
Print statements have been replaced by @info logging. I will release a new package version soon including this and some other updates

**Comment by ma-sadeghi** [comment]
Thanks!
