### ISSUE TITLE
Paper citation

### ISSUE THREAD

**Issue by Matheus-gif** [MaximeVH/EquivalentCircuits.jl#33]
Greetings everyone,

I'm currently working on a paper regarding electrocatalysis and am using this package to fit an equivalent circuit for my electrochemical systems. I would like to reference this package in my paper. Could someone direct me to the repository's preferred citation format, or let me know if there's an official way to reference this tool?

Thank you everyone in advance.

**Comment by MaximeVH** [comment]
Hi Matheus,

This package is linked to the publication: 

"Practical Equivalent Electrical Circuit Identification for Electrochemical Impedance Spectroscopy Analysis With Gene Expression Programming"

Which you can find on the following link:

https://ieeexplore.ieee.org/document/9539171

Kind regards,
Maxime
