### ISSUE TITLE
Extract the estimated circuit parameters directly from the evolution elite

### ISSUE THREAD

**Issue by RunzeZhang123** [MaximeVH/EquivalentCircuits.jl#36]
Hey Maxime,

We noticed that when outputting the elite from the evolution process, you used parameteroptimisation to refit the best candidate. Could you please explain why that is necessary? In my opinion, the refit process may alter the circuit fitness to make it not the most competitive one anymore because of the multi-linear fit algorithms' stochastic behavior. Would it be better to just use the parameters estimated during the evolutionary process?
`EquivalentCircuit(best_circuit,parameteroptimisation(best_circuit,measurements,frequencies))`

Thanks!

**Comment by MaximeVH** [comment]
Hey Runze, 

My reasoning was that the parameters estimated during the evolutionary process deal with a trade-off between not taking too long and getting a good fit. The optimisation in the `parameter optimisation` function does a more thorough optimisation, which takes more time. I expected it to slightly further improve the fit of the final circuit, though this may not always be the case.

**Comment by MaximeVH** [comment]
I removed the finetuning step, such that the parameters obtained through GEP are returned
