### ISSUE TITLE
Performance of impedance.py vs. EquivalentCircuits.jl

### ISSUE THREAD

**Issue by sindresops** [MaximeVH/EquivalentCircuits.jl#5]
I compared Impedance.py through PyCall.jl to EquivalentCircuits.jl. Naively I thought that Julia would out-perform Python. This quick test showed a ~25X speed advantage for the Python module. Of course the Julia module does not require the initial guess for circuit components. 

<img width="648" alt="image" src="https://user-images.githubusercontent.com/29738855/196182009-c4df8902-3fa7-4af2-8fc7-399a52534a1f.png">

I did a second test with the example data included in the EquivalentCitcuits.jl Readme.md. The time difference is roughly the same. 

<img width="704" alt="image" src="https://user-images.githubusercontent.com/29738855/196186432-7e96b291-da58-467e-b139-4b90faf89bac.png">

However, if I enter nonsensical values for the initual guess for the Python module, the fit misses the real data completely. 

So I suppose the trade-off here is convenience vs. speed?

Is it on the roadmap to include an optional initial guess for the component values?

**Comment by MaximeVH** [comment]
Thank you for your feedback. An advantage of the optimization methods used in this module is that they should work regardless of initial guesses. I could include an optional argument to allow users to provide initial component parameter guesses. There are also some opportunities to leverage Julia's speed advantage for this package, which I'm considering to implement at a later stage.

**Comment by sindresops** [comment]
Thanks for the reply! I will be familiarizing myself with the code and see if I can spot some performance traps :) 

I think an optional argument for initial guess would be a great addition.

**Comment by sindresops** [comment]
Definitely the parameter estimation that takes time. BlackBoxOptim.jl dominating the execution time.

![image](https://user-images.githubusercontent.com/29738855/196382604-1676c051-b640-4fba-aec7-b58f7707c497.png)

I tried it with adding an optional initial guess `x0`. Just modifying the last unit test to take on two different guesses. The last one is the output from the parameter optimization without passing the optional argument.

![image](https://user-images.githubusercontent.com/29738855/196431940-f6b1cb7a-7b3d-44d4-8374-7811cdb9c78f.png)

It does not improve by orders of magnitude, but comes a little bit closer to Impedance.py. 

Reducing MaxSteps from 170000 to 70000 linearly decreases execution time, without loss in accuracy for the example data in `runtests.jl`.

![image](https://user-images.githubusercontent.com/29738855/196433977-9d0c4ef8-e517-425d-bdfc-b4f56caaa91e.png)

So I guess this optimization method does not tremendously benefit from the initial guess. I also tried modifying the SearchRange algorithm, but it did not change anything :)

I am curious as to what speed optimizations you were considering?

**Comment by richinex** [comment]
It is interesting to stumble across this great package. I am definitely gonna try library out since I have just started working with Julia . Meanwhile @sindresops I have built two python packages for multidimensional fitting of impedance spectra (pymultieis and pymultipleis - written in PyTorch and Jax respectively). You might wanna try it out. I also described in the examples how to use it to fit a single spectra. 

I had to convert some of my codebase into Julia and noticed some of the concerns you raised. My take is that the optimization libraries in Julia are maybe not as optimized as they should be. I raised this same issue in Julia discourse and worked with some people to optimize my objective function as best as possible. Yet my python code still seems a little faster especially the one written in JAX (we could say that the python is just a wrapper anyway)

Concerning why impedancepy sometimes fail to fit when the initial values are far from optimal, i guess its because Levenberg Macquardt algorithm is sensitive to initial values. Also impedancepy uses scipy curve fit which employs numerical finite differencies. I implemented autodifferentiation and can see that my algorithm fits where impedancepy fails even when you use same initial values for both.

**Comment by sindresops** [comment]
Thanks for pointing me to those packages @richinex. I will definitely give them a go. I feel like this will end up with me integrating all four.

**Comment by StefanPofahl** [comment]
I took a while to figure out, how to simulate the impedance, based on the equivalent circuit model and it its parameters.
To help others here are the necessary code lines:
```
circuit_model = "R1-[C2,R3-[C4,R5]]"
circuit_params = parameteroptimisation(circuit_model, file_name_impedance_measurement)
circfunc = EquivalentCircuits.circuitfunction(circuit_model)
impedance_simulated = EquivalentCircuits.simulateimpedance_noiseless(circfunc, circuit_params, frequency_values)
```

**Comment by sindresops** [comment]
> Thank you for your feedback. An advantage of the optimization methods used in this module is that they should work regardless of initial guesses. I could include an optional argument to allow users to provide initial component parameter guesses. There are also some opportunities to leverage Julia's speed advantage for this package, which I'm considering to implement at a later stage.

PR generated: https://github.com/MaximeVH/EquivalentCircuits.jl/pull/13

It seems to be quite a lot faster if you do a perfect guess (10X). I am sure that might come in handy

**Comment by sindresops** [comment]
> [...] There are also some opportunities to leverage Julia's speed advantage for this package, which I'm considering to implement at a later stage.

You mention speed advantages. If you were to point me in a direction, where would you be looking to optimize first?

**Comment by MaximeVH** [comment]
The package's `circuit_evolution()` function uses some string processing (the manipulation and generation of strings), which has been reported as not being a strength of Julia. Suitable alternatives or improvements to this string processing could increase speed, though maybe not by a lot, as the optimization algorithms are the rate-limiting step. 

As for the parameter optimization, a new option has been added in this repo (not registered yet) where you can input other optimization algorithms from the [BlaxBoxOptim package](https://github.com/robertfeldt/BlackBoxOptim.jl). You could experiment with different optimization algorithms for the circuits you're fitting and see which trade-off between speed and performance is most suitable.
