### ISSUE TITLE
Pakage Announcement is missing for "EquivalentCircuits.jl"

### ISSUE THREAD

**Issue by StefanPofahl** [MaximeVH/EquivalentCircuits.jl#6]
First of all thank you very much for your great package!!!
It was not easy to find the package. 
Therefore, I propose that you make an anouncement for your package in:
[discourse.julialang.org/c/package-announcements](https://discourse.julialang.org/c/package-announcements/packages/47)

Best regards,

Stefan

**Comment by MaximeVH** [comment]
Thanks for your suggestion. I'll be sure to make an announcement there upon the next release.

Best regards,

Maxime

**Comment by StefanPofahl** [comment]
I am looking foreward :-)
